version: '3'

services:
  default-app-name:
    user: vscode
    env_file: devcontainer.env
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspace
      # IF YOU NEED CONNECTION TO AWS
      #- ~/.aws:/home/vscode/.aws
      # 
      #
      # Uncomment the relevant line for your OS to use Terraform Cloud
      # Windows (uncomment the following line)
      # - ${APPDATA}/terraform.rc:/home/vscode/.terraformrc
      # macOs/Linux (uncomment the following line)
      # - ~/.terraformrc:/home/vscode/.terraformrc

      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker.sock

      # SSM_PATH is used to set environment variables from SSM
      # More info: https://hub.docker.com/r/base2/awsenv/

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    networks:
      default:
        aliases:
          - workspace
          - ubuntu
